add optimism l1 bridge tests
antefinance/ante-community-tests pull request #192
Opened 2023-03-21 17:36 UTC by deemabot

2023-04-03 05:21 UTC, danielcrt requested changes
Tiny code styling suggestion. Everything else looks great! 💯

2023-04-03 05:21 UTC, danielcrt commented on contracts/optimism_bridge/AnteOptimismL1BridgeTokenSolvencyTest.sol
> +interface L1StandardBridge {
Tiny code styling suggestion: rename to `IL1StandardBridge` (prefix with capital "i")

2023-04-03 16:38 UTC, abitwhaleish commented
one of the tests is in the compound folder instead of OP bridge

2023-06-20 07:10 UTC, delalunia approved these changes

2023-06-20 07:22 UTC, merged